<?php /** @var \Mirasvit\Rewards\Block\Buttons\Facebook\Like $block */ ?>
<div class="buttons-facebook-like reward-custom-icon">
    <div class="fb-like" data-href="<?= $block->getEncodedPageUrl()?>"
         data-layout="button_count"
         data-action="like"
         data-show-faces="false"
         data-share="false"
         data-font="arial"
         data-colorscheme="light"></div>
    <?php if ($block->getEstimatedEarnPoints() > 0): ?>
        <?php if ($block->isAuthorized() && !$block->isLiked()): ?>
            <div id='facebook-message'>
            <?= __('Like this page and earn %1',  $this->helper('Mirasvit\Rewards\Helper\Data')->formatPoints($block->getEstimatedEarnPoints())); ?>
            </div>
        <?php endif; ?>
    <?php endif; ?>
</div>