<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>

<?php /** @var \Magento\Framework\Pricing\Render\Amount $block */ ?>

<span class="price-container <?php /* @escapeNotVerified */ echo $block->getAdjustmentCssClasses() ?>"
      <?php echo $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>
          <?php if ($block->getDisplayLabel()): ?>
        <span class="price-label"><?php /* @escapeNotVerified */ echo $block->getDisplayLabel(); ?></span>
    <?php endif; ?>
    <span <?php if ($block->getPriceId()): ?> id="<?php /* @escapeNotVerified */ echo $block->getPriceId() ?>"<?php endif; ?>
    <?php echo($block->getPriceDisplayLabel()) ? 'data-label="' . $block->getPriceDisplayLabel() . $block->getPriceDisplayInclExclTaxes() . '"' : '' ?>
                                              data-price-amount="<?php /* @escapeNotVerified */ echo $block->getDisplayValue(); ?>"
                                              data-price-type="<?php /* @escapeNotVerified */ echo $block->getPriceType(); ?>"
                                              class="price-wrapper <?php /* @escapeNotVerified */ echo $block->getPriceWrapperCss(); ?>"
                                              <?php echo $block->getSchema() ? ' itemprop="price"' : '' ?>>
                                              <?php /* @escapeNotVerified */ echo $block->formatCurrency($block->getDisplayValue(), (bool) $block->getIncludeContainer()) ?>
    </span>
    <?php
//    $specialprice = '';
//    $orgprice = '';
//    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product'); //get current 
//    //echo $product['price'];exit;
//    $orgprice = $product->getPrice();
//    $specialprice = $product->getSpecialPrice();
//    $specialfromdate = $product->getSpecialFromDate();
//    $specialtodate = $product->getSpecialToDate();
//    echo $orgprice;
//    echo $specialprice;
//    
//    $today = time();
//    if (!$specialprice)
//        $specialprice = $orgprice;
//    if ($specialprice < $orgprice) {
//        if ((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))) {
//            if ($_product_label_config['sale_label_percent']) {
//                $save_percent = 100 - round(($specialprice / $orgprice) * 100);
//                $product_label .= '<div class="product-label sale-label">' . '-' . $save_percent . '%' . '</div>';
//                echo $product_label;
//            } 
//        }
//    }
    ?>    
    <?php if ($block->hasAdjustmentsHtml()): ?>
        <?php echo $block->getAdjustmentsHtml() ?>
    <?php endif; ?>
    <?php if ($block->getSchema()): ?>
        <meta itemprop="priceCurrency" content="<?php /* @escapeNotVerified */ echo $block->getDisplayCurrencyCode() ?>" />
    <?php endif; ?>
</span>
