<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_call = $block->getAtCall();
$om = \Magento\Framework\App\ObjectManager::getInstance();
$manager = $om->get('Magento\Store\Model\StoreManagerInterface');
$stId = $manager->getStore()->getId();
//echo $block->getStore()->getId();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

$_code = $block->getAtCode();
$_className = $block->getCssClass();
$_attributeLabel = $block->getAtLabel();
$_attributeType = $block->getAtType();
$_attributeAddAttribute = $block->getAddAttribute();
//$_settingHelper = $this->helper('Emthemes\ThemeSettings\Helper\Data');
if ($_attributeLabel && $_attributeLabel == 'default') {
    $_attributeLabel = $_product->getResource()->getAttribute($_code)->getFrontendLabel();
}
if ($_attributeType && $_attributeType == 'text') {
    $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : '';
} else {
    $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code);
}
?>

<?php
if ($_attributeValue != '') {

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $storeManager->getStore()->getBaseUrl();
    ?>
<span class="chart-icon"><img src="http://www.firstlite.com/media/wysiwyg/icons/icons-sizingchart-white.png" alt="Sizing Chart"/></span>
    <a class="size_link" href="<?php echo $storeManager->getStore()->getBaseUrl() . $_attributeValue; ?>" target="_blank">Sizing Chart</a>

    <?php /* <img src="<?php echo $mediaUrl . '/catalog/product/' . $_attributeValue; ?>" alt="Size Chart" /> */ ?>
<?php }; ?>
<?php
//endif;
?>


